// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
	"nav": {
		"home": "Home",
		"features": "Functies",
		"pricing": "Prijzen"
	},
	"footer": {
		"builtBy": "Gebouwd door"
	}
};
export default messages;